### ISSUE TITLE
New release on Maven Central

### ISSUE THREAD

**Issue by rendaw** [square/gifencoder#17]
If it's not too much to ask for, would it be possible to push a new version to Maven Central?

**Comment by JakeWharton** [comment]
I can do it this week unless @dlubarov wants to hold it for any reason.

**Comment by dlubarov** [comment]
Please go ahead when you have a chance @JakeWharton

**Comment by JakeWharton** [comment]
0.10.0 released.

**Comment by JakeWharton** [comment]
Might take 15m - 1hr to show up on Maven Central.

**Comment by rendaw** [comment]
Many thanks!
