### ISSUE TITLE
Do you have any report for the performance?

### ISSUE THREAD

**Issue by bearprada** [square/gifencoder#6]
I had implemented the Gif Encoder feature in Java, but I got the pool performance, so we wrote it in C++ here.

https://github.com/cardinalblue/fast-gif-codec-android

but the performance isn't good enough (compare with iOS devices)

**Comment by JakeWharton** [comment]
We don't, no. It was built for a specific use case where performance wasn't
the primary goal. I'd be happy to see some numbers if you want to run some
benchmarks.

**Comment by bearprada** [comment]
sounds great, I will do it this weekend

**Comment by nvtuan305** [comment]
@bearprada Did you run some benchmarks? Could you give me performance results? I am using https://github.com/waynejo/android-ndk-gif, but the performances seem to be not good.
Thank you!
